### ISSUE TITLE
Jekyl build fails with permission issue

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#274] opened 2021-01-31 08:22 UTC
Not sure what this is about but after one of my recent commits to changes branch:

```
There was an error while trying to write to `/srv/jekyll/Gemfile.lock`. It is
likely that you need to grant write permissions for that path.
```

**Comment by ann0see** [comment] 2021-01-31 10:04
Yes. Had this issue too. No idea what the problem is. Maybe you need to chmod this file.

**Comment by gilgongo** [comment] 2021-01-31 10:43
Heh - I don't even know what server it's referring to so that I could chmod it!

**Comment by pljones** [comment] 2021-01-31 11:51
What emitted the error?

**Comment by gilgongo** [comment] 2021-01-31 12:16
A [build script](https://github.com/jamulussoftware/jamuluswebsite/runs/1800411587?check_suite_focus=true) on Github, I assume. Is this related to the recent change to the jamulus organisation?

**Comment by pljones** [comment] 2021-01-31 14:16
What I mean is, can you provide a bit more context.  There's no way to investigate currently.

**Comment by gilgongo** [comment] 2021-01-31 15:29
1. I edited a page on the changes branch using GitHub web and commited it in the usual way.
2. Next thing I knew I had a notification email with the link above in it.

**Comment by pljones** [comment] 2021-01-31 16:49
OK, I didn't see the link...  Half asleep still today...

Hm, the previous successful runs look different....  It looks like you didn't go through a pull request, merge?  The previous ones that work appear to run the build on merge....  Maybe there's a difference for the push vs merge flows?

https://github.com/jamulussoftware/jamuluswebsite/commits/changes

**Comment by gilgongo** [comment] 2021-02-01 08:12
I tried `chmod a+w /srv/jekyll/Gemfile.lock` but that didn't work.  Tried a pull request instead and it did work. Hm. I note GitHub puts "(pull request)" at the end of the script name it runs. Are there two of them?

**Comment by ann0see** [comment] 2021-02-01 08:18
Strange. There's another issue with PRs too: they don't get the result of the Jekyll checks and therefore block merging. Maybe we must re-implement the GH Actions here?

**Comment by gilgongo** [comment] 2021-02-01 08:21
Feel like it - although why exactly is unclear.

**Comment by ann0see** [comment] 2021-02-05 19:41
A bit exhausted today and I have a few other things to do. If somebody else wants to have a look at this I'd be glad. Nevertheless, I've assigned myself to this one (but I'm happy if anybody else had a look at this).

**Comment by gilgongo** [comment] 2021-02-15 08:09
I had a look around for other people having similar issues but I'm afraid I got nowhere because I don't understand the underlying issues with Docker and GitHub. It doesn't seem to be a common problem for other as far as I can tell though.

**Comment by ann0see** [comment] 2021-02-15 08:13
My problem here is that I have no idea either. It seems to work at the moment. Only remark-lint fails.

**Comment by ann0see** [comment] 2021-03-24 17:11
Closed this since I think it doesn't come up anymore.

**Closed as completed** 2021-03-24 17:10 UTC
Labels: bug
