### ISSUE TITLE
Reference text for server option not matching language used in the app

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#958] opened 2023-08-06 20:30 UTC
The following line of text is referring to the Small Network Buffers option in the Running-a-Server page:

"Reduces latency if Clients connect with **Enable Small Network Buffers** option. Requires faster CPU to avoid dropouts, and more bandwidth to enabled Clients."

https://github.com/jamulussoftware/jamuluswebsite/blob/3020a2d48b853c0f5e315c81921fa247078a5f38/wiki/en/Running-a-Server.md?plain=1#L204C1-L204C1

The text is using "Enable Small Network Buffers", while "Enable" has been removed from the app.

**Comment by ann0see** [comment] 2023-08-06 20:34
Difficult thing. Do you think it's worth changing it? This means translators need to update it.

**Comment by henkdegroot** [comment] 2023-08-06 20:40
Not sure if it is worth the trouble but at least wanted to report it. Can also be updated in a future release.
Some translators may have spotted it, other may not have.

**Comment by pljones** [comment] 2023-08-07 17:45
Did I miss it?  Sorry... :(

**Comment by mcfnord** [comment] 2023-08-10 19:00
> Difficult thing. Do you think it's worth changing it? This means translators need to update it.

I wish any error was worth fixing, even in just the English. But that would introduce no-priority translation tasks. Don't translators receive a list of translations in a big pile and go to town on the native equivalents? Isn't this just one more lil translation task in a pile? How should I understand the translator tax?

**Comment by ann0see** [comment] 2023-08-10 19:36
Yes. Changes in the English version would be another string  which would show up on Weblate. 
The problem is that in some cases we have conflicts.

**Comment by mcfnord** [comment] 2023-08-10 20:25
What's an example? (I did a website translation into 4 other languages using robot and human translators once, but am not really an expert.)

**Comment by ann0see** [comment] 2023-08-10 20:46
The conflicts arise due to how our process works. 

Assume someone changes wiki/en/Getting-Started.md and rewrites a section on this page in English. Meanwhile a translator saw a typo in the paragraph which was rewritten and fixes it on Weblate while the section rewrite is not yet on Weblate. Now as soon as Weblate sees the rewrite of the English source and the typo fix it doesn't know what to do. This happens very often here.

**Comment by ignotus666** [comment] 2023-08-11 07:22
Or you can think of the conflicts in terms of GitHub pull requests (which is what it actually is - Weblate is just a front-end for a fork of our repos). While a Weblate PR is waiting to be merged, if you merge a change to the base branch that affects files in the PR you get conflicts, just like with any other PR. It's simply a matter of doing things in the right order.

Although we declare the state of translatable texts to be frozen and the idea is that they don't change any further until the release, issues with the source text often crop up during translation due to the fact that translators are poring over it sentence by sentence. Maybe we could have an additional "clean-up" round before release where these issues (like the one here) are addressed and those bits and pieces can get translated.

**Comment by mcfnord** [comment] 2023-08-12 07:28
I probably get all that. The Jamshack West and two other servers quote the slightly mistaken guidance:

> Please ensure **"Buffer Delay" is set to 2.67ms (64) and "Enable Small Network Buffers"** is **"Enabled"** in your **"Settings"** for lowest latency. 

At the end of the day, nothing catches on fire. I bet few people are tripped up by this. The human does the last mile of interpretation and everything's fine. I just don't want this kind of friction in my utopia.

**Comment by ann0see** [comment] 2023-08-12 20:53
I don't think we can do anything about that. You can try to get in contact with the server owners but if they don't respond it stays outdated.

**Comment by mcfnord** [comment] 2023-08-12 21:04
It's an anecdotal example of how our documentation, including its errors, gets propagated far and wide.

**Comment by ann0see** [comment] 2023-08-23 10:27
@henkdegroot @ignotus666 @jujudusud @trebmuh 

Would you mind that we lock Weblate, do the change and then do the translation for this?

**Comment by ignotus666** [comment] 2023-08-23 11:45
Fine by me.

**Comment by henkdegroot** [comment] 2023-08-23 11:58
In that case, should we also do #959 at the same time?

**Comment by pljones** [comment] 2023-08-23 15:20
If this is getting picked up for 3.11.0 or 3.10.0 please can it be assigned and added to the release.

**Comment by jujudusud** [comment] 2023-08-23 18:38
Ok for me. 958 and 959 ... no problem if this is needed or wanted for 3.10.0

**Closed as completed** 2023-08-24 12:51 UTC
Labels: bug
